version: '3'

services:
  postgres:
    container_name: payments_db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=payments-db
    networks:
      - spring-cloud-network

  app:
    container_name: payments-ms
    image: payments-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - spring-cloud-network
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payments-db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

networks:
  spring-cloud-network:
    driver: bridge