spring:
  application:
    name: 'payments-ms'
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: 'ecomm-user'
    password: 'start-password'
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://payment-postgres/payments-db?user=admin&password=admin&createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: 'true'
        format_sql: 'true'
        default_schema: ecomm_payments
    show-sql: 'false'
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: none

server:
  port: 8081
  address: 0.0.0.0